request_timeout 30;

server {
    host 127.0.0.1;
    ports 8080;
    client_max_body_size 16;

    error_page 413 www/errors/413.html;

    route / {
        root www;
        methods GET POST;
        index index.html;
        directory_listing off;
    }
}
