request_timeout 30;
cgi_timeout 5;

server {
    host 127.0.0.1;
    ports 8080;
    server_name localhost;
    client_max_body_size 8M;

    error_page 400 www/errors/400.html;
    error_page 403 www/errors/403.html;
    error_page 404 www/errors/404.html;
    error_page 405 www/errors/405.html;
    error_page 413 www/errors/413.html;
    error_page 500 www/errors/500.html;

    route / {
        root www;
        methods GET POST DELETE;
        index index.html;
        directory_listing off;
    }

    route /uploads {
        root www/uploads;
        methods GET POST DELETE;
        index index.html;
        directory_listing on;
        upload_store www/uploads;
    }

    route /listing {
        root www/listing;
        methods GET;
        directory_listing on;
    }

    route /cgi {
        root www/cgi;
        methods GET POST;
        cgi .py /usr/bin/python3;
    }

    route /old {
        methods GET;
        redirect 301 /;
    }
}
