server {
    host 127.0.0.1;
    ports 8080 8080;

    route / {
        root www;
        methods GET;
        index index.html;
        directory_listing off;
    }
}

server {
    host 127.0.0.1;
    ports 8081;

    route / {
        root www;
        methods GET;
        index index.html;
        directory_listing off;
    }
}
