request_timeout 30;

server {
    host 127.0.0.1;
    ports 8080;
    server_name alpha.test;

    route / {
        root www;
        methods GET;
        index index.html;
        directory_listing off;
    }
}

server {
    host 127.0.0.1;
    ports 8080;
    server_name beta.test;

    route / {
        root www/uploads;
        methods GET;
        index index.html;
        directory_listing off;
    }
}
